const booksData = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        category: "Fiction",
        rating: 4.5,
        pages: 180,
        year: 1925,
        cover: "https://covers.openlibrary.org/b/id/8225261-L.jpg",
        description: "Set in the Jazz Age of the 1920s, this masterpiece chronicles the tragic pursuit of the American Dream through the enigmatic millionaire Jay Gatsby's hopeless and ultimately doomed love for the beautiful but shallow Daisy Buchanan, offering a profound critique of wealth, class, and the hollow core of the American aristocracy.",
        tags: ["Classic", "American Literature", "Romance"],
        featured: true,
        newArrival: false
    },
    {
        id: 2,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        category: "Fiction",
        rating: 4.8,
        pages: 281,
        year: 1960,
        cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
        description: "Through the eyes of young Scout Finch, this Pulitzer Prize-winning novel explores racial injustice and moral growth in 1930s Alabama as her father, attorney Atticus Finch, defends a Black man falsely accused of rape, delivering an unforgettable meditation on empathy, courage, and the loss of innocence.",
        tags: ["Classic", "Drama", "Social Justice"],
        featured: true,
        newArrival: false
    },
    {
        id: 3,
        title: "1984",
        author: "George Orwell",
        category: "Science Fiction",
        rating: 4.7,
        pages: 328,
        year: 1949,
        cover: "https://covers.openlibrary.org/b/id/8575111-L.jpg",
        description: "In a chilling dystopian future where three superstates control the world, Winston Smith dares to rebel against the totalitarian Party through a forbidden love affair, discovering the terrifying power of Big Brother, perpetual surveillance, and the systematic destruction of truth in this seminal political allegory.",
        tags: ["Dystopian", "Political Fiction", "Classic"],
        featured: true,
        newArrival: false
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        category: "Romance",
        rating: 4.6,
        pages: 432,
        year: 1813,
        cover: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
        description: "Set in rural England, this witty and timeless classic follows the spirited Elizabeth Bennet as she navigates matters of marriage, morality, and misunderstandings with the proud and aloof Mr. Darcy, delivering a masterful exploration of class, family, and the complexities of love and first impressions.",
        tags: ["Classic", "Romance", "British Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 5,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        category: "Fiction",
        rating: 4.3,
        pages: 234,
        year: 1951,
        cover: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
        description: "The iconic tale of disaffected youth follows sixteen-year-old Holden Caulfield after his expulsion from prep school, as he wanders the streets of New York City grappling with alienation, identity, and the painful transition from innocence to adulthood in this groundbreaking portrait of teenage angst.",
        tags: ["Classic", "Coming-of-Age", "American Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 6,
        title: "The Silent Patient",
        author: "Alex Michaelides",
        category: "Mystery",
        rating: 4.5,
        pages: 336,
        year: 2019,
        cover: "https://covers.openlibrary.org/b/id/10389354-L.jpg",
        description: "A psychological thriller that unravels the story of Alicia Berenson, a celebrated painter who shoots her husband five times and then refuses to speak another word, told through the determined efforts of psychotherapist Theo Faber to uncover the truth behind her silence and his own hidden obsessions.",
        tags: ["Thriller", "Psychological", "Suspense"],
        featured: true,
        newArrival: true
    },
    {
        id: 7,
        title: "Gone Girl",
        author: "Gillian Flynn",
        category: "Mystery",
        rating: 4.4,
        pages: 432,
        year: 2012,
        cover: "https://covers.openlibrary.org/b/id/8477223-L.jpg",
        description: "On their fifth wedding anniversary, Nick Dunne's wife Amy disappears, and the media frenzy reveals a marriage built on secrets, lies, and manipulation in this twist-filled psychological thriller that explores the dark side of modern relationships and the performative nature of identity.",
        tags: ["Thriller", "Psychological", "Crime"],
        featured: false,
        newArrival: false
    },
    {
        id: 8,
        title: "The Girl with the Dragon Tattoo",
        author: "Stieg Larsson",
        category: "Mystery",
        rating: 4.3,
        pages: 480,
        year: 2005,
        cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
        description: "Disgraced journalist Mikael Blomkvist and brilliant but damaged hacker Lisbeth Salander form an unlikely alliance to investigate the decades-old disappearance of a wealthy industrialist's niece, uncovering a web of corruption, violence, and family secrets in this atmospheric Scandinavian noir.",
        tags: ["Thriller", "Crime", "Nordic Noir"],
        featured: false,
        newArrival: false
    },
    {
        id: 9,
        title: "Dune",
        author: "Frank Herbert",
        category: "Science Fiction",
        rating: 4.7,
        pages: 688,
        year: 1965,
        cover: "https://covers.openlibrary.org/b/id/11153217-L.jpg",
        description: "Set in the distant future amidst a feudal interstellar society, this epic saga follows young Paul Atreides as his family accepts control of the desert planet Arrakis, the only source of the most valuable substance in the universe, where he must navigate political betrayal, ecological warfare, and his own emerging prophetic powers.",
        tags: ["Sci-Fi", "Epic", "Space Opera"],
        featured: true,
        newArrival: false
    },
    {
        id: 10,
        title: "The Martian",
        author: "Andy Weir",
        category: "Science Fiction",
        rating: 4.6,
        pages: 369,
        year: 2011,
        cover: "https://covers.openlibrary.org/b/id/8108297-L.jpg",
        description: "During a mission to Mars, astronaut Mark Watney is presumed dead and left behind, but he survives and must rely on his ingenuity, scientific knowledge, and dark humor to grow food, generate water, and signal Earth for rescue in this gripping tale of survival against all odds.",
        tags: ["Sci-Fi", "Survival", "Space"],
        featured: false,
        newArrival: false
    },
    {
        id: 11,
        title: "Project Hail Mary",
        author: "Andy Weir",
        category: "Science Fiction",
        rating: 4.8,
        pages: 496,
        year: 2021,
        cover: "https://covers.openlibrary.org/b/id/10909258-L.jpg",
        description: "Awakening with amnesia aboard a spacecraft bound for a distant star, Ryland Grace must reconstruct his memory and mission: to save humanity from an extinction-level threat by solving an impossible scientific puzzle with the help of an unlikely alien partner in this thrilling, humor-filled space adventure.",
        tags: ["Sci-Fi", "Space", "Adventure"],
        featured: true,
        newArrival: true
    },
    {
        id: 12,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        category: "Fantasy",
        rating: 4.8,
        pages: 310,
        year: 1937,
        cover: "https://covers.openlibrary.org/b/id/8406786-L.jpg",
        description: "In this beloved prequel to The Lord of the Rings, comfortable hobbit Bilbo Baggins is recruited by the wizard Gandalf to join thirteen dwarves on a perilous quest to reclaim their stolen treasure from the fearsome dragon Smaug, embarking on an unexpected adventure that will test his courage and wit.",
        tags: ["Fantasy", "Adventure", "Classic"],
        featured: true,
        newArrival: false
    },
    {
        id: 13,
        title: "Harry Potter and the Sorcerer's Stone",
        author: "J.K. Rowling",
        category: "Fantasy",
        rating: 4.9,
        pages: 309,
        year: 1997,
        cover: "https://covers.openlibrary.org/b/id/10110415-L.jpg",
        description: "The magical beginning of a seven-book saga introduces Harry Potter, an orphaned boy who discovers he is a wizard and is invited to attend Hogwarts School of Witchcraft and Wizardry, where he makes lifelong friends, faces his first confrontation with the dark wizard Voldemort, and learns the truth about his parents' mysterious deaths.",
        tags: ["Fantasy", "Magic", "Young Adult"],
        featured: true,
        newArrival: false
    },
    {
        id: 14,
        title: "A Game of Thrones",
        author: "George R.R. Martin",
        category: "Fantasy",
        rating: 4.7,
        pages: 835,
        year: 1996,
        cover: "https://covers.openlibrary.org/b/id/8479759-L.jpg",
        description: "The first volume of the epic fantasy series A Song of Ice and Fire introduces a sprawling cast of characters across the Seven Kingdoms of Westeros, where noble families vie for control of the Iron Throne while an ancient evil awakens beyond the Wall and a exiled princess plots her return.",
        tags: ["Fantasy", "Epic", "Political"],
        featured: false,
        newArrival: false
    },
    {
        id: 15,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        category: "Non-Fiction",
        rating: 4.6,
        pages: 443,
        year: 2011,
        cover: "https://covers.openlibrary.org/b/id/8406550-L.jpg",
        description: "From the Stone Age to the Silicon Age, this groundbreaking bestseller explores how Homo sapiens became the dominant species on Earth, examining the cognitive, agricultural, and scientific revolutions that shaped our biology, societies, and collective future through a provocative and accessible lens.",
        tags: ["History", "Science", "Anthropology"],
        featured: true,
        newArrival: false
    },
    {
        id: 16,
        title: "Atomic Habits",
        author: "James Clear",
        category: "Self-Help",
        rating: 4.8,
        pages: 320,
        year: 2018,
        cover: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
        description: "A revolutionary guide to building good habits and breaking bad ones, this practical manual reveals how tiny changes in behavior can lead to remarkable results by focusing on the science of habit formation, identity-based change, and the compound power of small improvements made consistently over time.",
        tags: ["Self-Help", "Productivity", "Psychology"],
        featured: true,
        newArrival: true
    },
    {
        id: 17,
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        category: "Psychology",
        rating: 4.5,
        pages: 499,
        year: 2011,
        cover: "https://covers.openlibrary.org/b/id/8301024-L.jpg",
        description: "Nobel laureate Daniel Kahneman explores the two systems that drive our thinking: the fast, intuitive, and emotional System 1, and the slow, deliberate, and logical System 2, revealing how these systems shape our judgments, decisions, and ultimately our understanding of reality and happiness.",
        tags: ["Psychology", "Economics", "Decision Making"],
        featured: false,
        newArrival: false
    },
    {
        id: 18,
        title: "Steve Jobs",
        author: "Walter Isaacson",
        category: "Biography",
        rating: 4.5,
        pages: 656,
        year: 2011,
        cover: "https://covers.openlibrary.org/b/id/7327734-L.jpg",
        description: "Based on more than forty interviews with Steve Jobs conducted over two years, as well as interviews with over a hundred family members, friends, adversaries, and colleagues, this definitive biography reveals the visionary entrepreneur's obsessive perfectionism, creative genius, and complex personal life.",
        tags: ["Biography", "Technology", "Business"],
        featured: false,
        newArrival: false
    },
    {
        id: 19,
        title: "Becoming",
        author: "Michelle Obama",
        category: "Biography",
        rating: 4.7,
        pages: 448,
        year: 2018,
        cover: "https://covers.openlibrary.org/b/id/8544943-L.jpg",
        description: "The former First Lady's powerful memoir chronicles her journey from childhood on the South Side of Chicago to her years as one of the most influential women in the world, offering an intimate portrait of her life, family, public service, and the experiences that shaped her identity and values.",
        tags: ["Memoir", "Politics", "Inspiration"],
        featured: true,
        newArrival: false
    },
    {
        id: 20,
        title: "The Shining",
        author: "Stephen King",
        category: "Horror",
        rating: 4.5,
        pages: 447,
        year: 1977,
        cover: "https://covers.openlibrary.org/b/id/8477222-L.jpg",
        description: "Jack Torrance accepts a position as winter caretaker of the isolated Overlook Hotel, hoping to overcome his writer's block and repair his family relationships, but the hotel's supernatural evil influences him toward madness and violence, threatening his wife Wendy and their psychic son Danny in this iconic horror masterpiece.",
        tags: ["Horror", "Psychological", "Supernatural"],
        featured: false,
        newArrival: false
    },
    {
        id: 21,
        title: "It",
        author: "Stephen King",
        category: "Horror",
        rating: 4.4,
        pages: 1138,
        year: 1986,
        cover: "https://covers.openlibrary.org/b/id/8231432-L.jpg",
        description: "In this epic horror novel, a group of childhood friends confronts an ancient evil that takes the form of Pennywise the Dancing Clown, emerging every 27 years to prey on the children of Derry, Maine, exploring themes of trauma, memory, and the resilience of friendship in the face of unspeakable terror.",
        tags: ["Horror", "Supernatural", "Coming-of-Age"],
        featured: false,
        newArrival: false
    },
    {
        id: 22,
        title: "The Book Thief",
        author: "Markus Zusak",
        category: "Historical Fiction",
        rating: 4.6,
        pages: 552,
        year: 2005,
        cover: "https://covers.openlibrary.org/b/id/8360061-L.jpg",
        description: "Narrated by Death itself, this unforgettable novel follows nine-year-old Liesel Meminger as she finds solace in stealing books and sharing them with others in Nazi Germany, forming a powerful bond with her accordion-playing foster father and a Jewish fighter hidden in her basement during World War II.",
        tags: ["Historical", "WWII", "Young Adult"],
        featured: true,
        newArrival: false
    },
    {
        id: 23,
        title: "All the Light We Cannot See",
        author: "Anthony Doerr",
        category: "Historical Fiction",
        rating: 4.5,
        pages: 531,
        year: 2014,
        cover: "https://covers.openlibrary.org/b/id/8225232-L.jpg",
        description: "This Pulitzer Prize-winning novel intertwines the lives of Marie-Laure, a blind French girl, and Werner, a German boy with a talent for radios, whose paths collide in occupied France during World War II, illuminating the extraordinary ways that hope and humanity persist amid the devastation of war.",
        tags: ["Historical", "WWII", "Literary Fiction"],
        featured: false,
        newArrival: false
    },
    {
        id: 24,
        title: "The Notebook",
        author: "Nicholas Sparks",
        category: "Romance",
        rating: 4.3,
        pages: 214,
        year: 1996,
        cover: "https://covers.openlibrary.org/b/id/8406809-L.jpg",
        description: "A timeless love story spanning decades, this beloved novel tells of Noah Calhoun and Allie Hamilton, a young couple from different social classes whose summer romance is tested by war, family opposition, and time itself, narrated through a touching story-within-a-story framework that explores enduring love and sacrifice.",
        tags: ["Romance", "Drama", "Love Story"],
        featured: false,
        newArrival: false
    },
    {
        id: 25,
        title: "Outlander",
        author: "Diana Gabaldon",
        category: "Romance",
        rating: 4.6,
        pages: 850,
        year: 1991,
        cover: "https://covers.openlibrary.org/b/id/8366152-L.jpg",
        description: "During a second honeymoon in Scotland, World War II nurse Claire Randall walks through a stone circle and is transported back to 1743, where she encounters Highland warrior Jamie Fraser and becomes entangled in the Jacobite uprising, weaving together historical adventure, time travel, and passionate romance.",
        tags: ["Romance", "Historical", "Time Travel"],
        featured: false,
        newArrival: false
    },
    {
        id: 26,
        title: "The Lean Startup",
        author: "Eric Ries",
        category: "Business",
        rating: 4.4,
        pages: 336,
        year: 2011,
        cover: "https://covers.openlibrary.org/b/id/8302076-L.jpg",
        description: "A revolutionary approach to building successful startups, this essential guide introduces the build-measure-learn feedback loop, emphasizing rapid experimentation, continuous innovation, and the importance of validated learning to help entrepreneurs create products that customers actually want and build sustainable businesses.",
        tags: ["Business", "Entrepreneurship", "Startup"],
        featured: false,
        newArrival: false
    },
    {
        id: 27,
        title: "Zero to One",
        author: "Peter Thiel",
        category: "Business",
        rating: 4.5,
        pages: 224,
        year: 2014,
        cover: "https://covers.openlibrary.org/b/id/8302089-L.jpg",
        description: "Legendary entrepreneur Peter Thiel presents a contrarian blueprint for building the future, arguing that true innovation involves creating something entirely new (going from zero to one) rather than copying existing models, with insights on competition, monopoly, and the secrets of breakthrough companies.",
        tags: ["Business", "Entrepreneurship", "Innovation"],
        featured: false,
        newArrival: true
    },
    {
        id: 28,
        title: "Charlotte's Web",
        author: "E.B. White",
        category: "Children",
        rating: 4.7,
        pages: 184,
        year: 1952,
        cover: "https://covers.openlibrary.org/b/id/8231987-L.jpg",
        description: "A timeless tale of friendship and loyalty, this Newbery Honor book tells the story of Wilbur the pig and Charlotte the spider, whose clever web messages save him from slaughter, celebrating the power of words, the bond between unlikely friends, and the wonder of life on a rural farm.",
        tags: ["Children", "Classic", "Animals"],
        featured: false,
        newArrival: false
    },
    {
        id: 29,
        title: "The Very Hungry Caterpillar",
        author: "Eric Carle",
        category: "Children",
        rating: 4.8,
        pages: 26,
        year: 1969,
        cover: "https://covers.openlibrary.org/b/id/8231990-L.jpg",
        description: "This iconic picture book follows a tiny caterpillar's journey as he eats his way through a variety of foods before transforming into a beautiful butterfly, teaching children about counting, days of the week, and the miraculous process of metamorphosis through vibrant collage illustrations.",
        tags: ["Children", "Picture Book", "Educational"],
        featured: false,
        newArrival: false
    },
    {
        id: 30,
        title: "Meditations",
        author: "Marcus Aurelius",
        category: "Philosophy",
        rating: 4.6,
        pages: 304,
        year: 180,
        cover: "https://covers.openlibrary.org/b/id/8302046-L.jpg",
        description: "Written by Roman Emperor Marcus Aurelius as a personal guide to self-improvement, these private notes of Stoic philosophy offer profound wisdom on resilience, virtue, and the pursuit of inner peace, providing timeless guidance for navigating life's challenges with clarity, discipline, and emotional strength.",
        tags: ["Philosophy", "Stoicism", "Classic"],
        featured: false,
        newArrival: false
    },
    {
        id: 31,
        title: "The Alchemist",
        author: "Paulo Coelho",
        category: "Fiction",
        rating: 4.5,
        pages: 208,
        year: 1988,
        cover: "https://covers.openlibrary.org/b/id/8231421-L.jpg",
        description: "A shepherd boy named Santiago journeys from Spain to Egypt in search of a treasure buried in the Egyptian pyramids, discovering that the real treasure is the wisdom gained through pursuing his Personal Legend, in this allegorical tale about destiny, dreams, and the transformative power of following one's heart.",
        tags: ["Fiction", "Philosophy", "Adventure"],
        featured: true,
        newArrival: false
    },
    {
        id: 32,
        title: "Brave New World",
        author: "Aldous Huxley",
        category: "Science Fiction",
        rating: 4.4,
        pages: 288,
        year: 1932,
        cover: "https://covers.openlibrary.org/b/id/8231424-L.jpg",
        description: "In a futuristic World State where humans are genetically engineered and conditioned for predetermined roles, citizen Bernard Marx visits a Savage Reservation and returns with John, a man raised on Shakespeare and suffering, challenging the foundations of this seemingly perfect but dehumanizing society in Huxley's prescient dystopian masterpiece.",
        tags: ["Dystopian", "Sci-Fi", "Classic"],
        featured: false,
        newArrival: false
    },
    {
        id: 33,
        title: "The Lord of the Rings",
        author: "J.R.R. Tolkien",
        category: "Fantasy",
        rating: 4.9,
        pages: 1216,
        year: 1954,
        cover: "https://covers.openlibrary.org/b/id/8231427-L.jpg",
        description: "An epic high fantasy trilogy follows hobbit Frodo Baggins and the Fellowship of the Ring on a perilous quest to destroy the One Ring and defeat the dark lord Sauron, weaving together themes of friendship, courage, sacrifice, and the eternal struggle between good and evil in one of the most influential works of imaginative fiction ever written.",
        tags: ["Fantasy", "Epic", "Adventure"],
        featured: true,
        newArrival: false
    },
    {
        id: 34,
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        category: "Fiction",
        rating: 4.5,
        pages: 671,
        year: 1866,
        cover: "https://covers.openlibrary.org/b/id/8231430-L.jpg",
        description: "This psychological masterpiece follows Raskolnikov, a destitute former law student in St. Petersburg who formulates and executes a plan to murder an unscrupulous pawnbroker, then grapples with overwhelming guilt, paranoia, and philosophical debates about morality, redemption, and the nature of justice.",
        tags: ["Classic", "Psychological", "Russian Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 35,
        title: "The Count of Monte Cristo",
        author: "Alexandre Dumas",
        category: "Fiction",
        rating: 4.7,
        pages: 1276,
        year: 1844,
        cover: "https://covers.openlibrary.org/b/id/8231433-L.jpg",
        description: "Wrongly imprisoned for life, Edmond Dantès is dramatically rescued and discovers a vast treasure, transforming into the mysterious Count of Monte Cristo and dedicating his life to elaborate revenge against those who conspired against him, in this sweeping adventure of betrayal, justice, and redemption set in 19th-century France.",
        tags: ["Classic", "Adventure", "Historical"],
        featured: false,
        newArrival: false
    },
    {
        id: 36,
        title: "Jane Eyre",
        author: "Charlotte Bronte",
        category: "Romance",
        rating: 4.5,
        pages: 532,
        year: 1847,
        cover: "https://covers.openlibrary.org/b/id/8231436-L.jpg",
        description: "Orphaned and independent, Jane Eyre becomes a governess at Thornfield Hall, where she encounters the brooding, mysterious Mr. Rochester and must navigate love, social class, and dark secrets while maintaining her moral integrity and sense of self-worth in this groundbreaking Gothic romance.",
        tags: ["Classic", "Romance", "Gothic"],
        featured: false,
        newArrival: false
    },
    {
        id: 37,
        title: "Wuthering Heights",
        author: "Emily Bronte",
        category: "Romance",
        rating: 4.3,
        pages: 416,
        year: 1847,
        cover: "https://covers.openlibrary.org/b/id/8231439-L.jpg",
        description: "Set on the desolate Yorkshire moors, this intense and atmospheric novel tells the destructive, all-consuming love story of Heathcliff and Catherine Earnshaw, exploring themes of obsessive passion, revenge, social class, and the supernatural through a complex, multi-generational narrative structure.",
        tags: ["Classic", "Romance", "Gothic"],
        featured: false,
        newArrival: false
    },
    {
        id: 38,
        title: "Frankenstein",
        author: "Mary Shelley",
        category: "Horror",
        rating: 4.4,
        pages: 280,
        year: 1818,
        cover: "https://covers.openlibrary.org/b/id/8231442-L.jpg",
        description: "This groundbreaking Gothic novel tells the story of Victor Frankenstein, an ambitious young scientist who creates a grotesque but sapient creature in an unorthodox scientific experiment, exploring timeless questions about creation, responsibility, ambition, and what it means to be human in a tale that has become a cultural touchstone.",
        tags: ["Horror", "Classic", "Gothic"],
        featured: false,
        newArrival: false
    },
    {
        id: 39,
        title: "Dracula",
        author: "Bram Stoker",
        category: "Horror",
        rating: 4.3,
        pages: 418,
        year: 1897,
        cover: "https://covers.openlibrary.org/b/id/8231445-L.jpg",
        description: "Told through a series of letters, diary entries, and newspaper clippings, this epistolary novel introduces the iconic Count Dracula as he travels from Transylvania to England, preying on the blood of the living while a small group of determined individuals bands together to stop his reign of terror.",
        tags: ["Horror", "Classic", "Gothic"],
        featured: false,
        newArrival: false
    },
    {
        id: 40,
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        category: "Fiction",
        rating: 4.4,
        pages: 254,
        year: 1890,
        cover: "https://covers.openlibrary.org/b/id/8231448-L.jpg",
        description: "When handsome young Dorian Gray has his portrait painted, he makes a Faustian bargain, wishing to stay young and beautiful while the painting ages and changes to reflect his inner character, leading him down a path of hedonism, moral corruption, and tragedy in Wilde's only full-length novel.",
        tags: ["Classic", "Gothic", "Philosophy"],
        featured: false,
        newArrival: false
    },
    {
        id: 41,
        title: "Moby-Dick",
        author: "Herman Melville",
        category: "Fiction",
        rating: 4.2,
        pages: 720,
        year: 1851,
        cover: "https://covers.openlibrary.org/b/id/8231451-L.jpg",
        description: "Captain Ahab's obsessive quest for revenge against the great white whale that bit off his leg drives the narrative of this epic American novel, told through the eyes of Ishmael as he recounts the ill-fated voyage of the Pequod and the captain's monomaniacal pursuit that tests the limits of human will and sanity.",
        tags: ["Classic", "Adventure", "American Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 42,
        title: "War and Peace",
        author: "Leo Tolstoy",
        category: "Historical Fiction",
        rating: 4.6,
        pages: 1225,
        year: 1869,
        cover: "https://covers.openlibrary.org/b/id/8231454-L.jpg",
        description: "This monumental epic chronicles the lives of five aristocratic Russian families set against the backdrop of the Napoleonic Wars, weaving together personal drama, philosophical digressions, and historical events to explore the relationship between man's will and choice versus fate and history.",
        tags: ["Classic", "Historical", "Russian Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 43,
        title: "Anna Karenina",
        author: "Leo Tolstoy",
        category: "Romance",
        rating: 4.5,
        pages: 864,
        year: 1877,
        cover: "https://covers.openlibrary.org/b/id/8231457-L.jpg",
        description: "The tragic story of Anna Karenina, a married woman who falls in love with the dashing Count Vronsky, challenging the moral conventions of 19th-century Russian society, while running parallel to the story of Konstantin Levin's search for meaning and happiness in this masterpiece of realist fiction.",
        tags: ["Classic", "Romance", "Russian Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 44,
        title: "The Brothers Karamazov",
        author: "Fyodor Dostoevsky",
        category: "Fiction",
        rating: 4.7,
        pages: 824,
        year: 1880,
        cover: "https://covers.openlibrary.org/b/id/8231460-L.jpg",
        description: "Dostoevsky's final and most ambitious novel explores faith, doubt, free will, and family through the story of the Karamazov brothers, particularly the impulsive Dmitri, intellectual Ivan, saintly Alyosha, and their estranged father Fyodor, a lecherous and greedy man whose murder sets the stage for a profound philosophical drama.",
        tags: ["Classic", "Philosophy", "Russian Literature"],
        featured: false,
        newArrival: false
    },
    {
        id: 45,
        title: "Don Quixote",
        author: "Miguel de Cervantes",
        category: "Fiction",
        rating: 4.4,
        pages: 1072,
        year: 1605,
        cover: "https://covers.openlibrary.org/b/id/8231463-L.jpg",
        description: "This foundational work of modern Western literature follows the adventures of Alonso Quixano, an elderly gentleman who reads so many chivalric romances that he decides to become a knight-errant himself, dressing as Don Quixote and roaming the plains of La Mancha with his squire Sancho Panza in a satirical masterpiece.",
        tags: ["Classic", "Satire", "Adventure"],
        featured: false,
        newArrival: false
    },
    {
        id: 46,
        title: "One Hundred Years of Solitude",
        author: "Gabriel Garcia Marquez",
        category: "Fiction",
        rating: 4.6,
        pages: 417,
        year: 1967,
        cover: "https://covers.openlibrary.org/b/id/8231466-L.jpg",
        description: "A masterpiece of magical realism that chronicles seven generations of the Buendía family in the fictional Colombian town of Macondo, blending the extraordinary with the ordinary to create a dreamlike narrative that explores the cyclical nature of history, solitude, and the Latin American experience.",
        tags: ["Magical Realism", "Classic", "Latin American"],
        featured: true,
        newArrival: false
    },
    {
        id: 47,
        title: "The Hunger Games",
        author: "Suzanne Collins",
        category: "Science Fiction",
        rating: 4.5,
        pages: 374,
        year: 2008,
        cover: "https://covers.openlibrary.org/b/id/8231469-L.jpg",
        description: "In a dystopian future where the Capitol maintains control over twelve districts through fear, sixteen-year-old Katniss Everdeen volunteers to take her sister's place in the Hunger Games, a brutal televised competition where tributes must fight to the death, sparking a revolution through her defiance and survival skills.",
        tags: ["Dystopian", "Young Adult", "Action"],
        featured: false,
        newArrival: false
    },
    {
        id: 48,
        title: "The Fault in Our Stars",
        author: "John Green",
        category: "Romance",
        rating: 4.4,
        pages: 313,
        year: 2012,
        cover: "https://covers.openlibrary.org/b/id/8231472-L.jpg",
        description: "A heart-wrenching yet life-affirming love story between Hazel and Gus, two teenagers who meet at a cancer support group and fall in love despite the terminal nature of their illnesses, exploring profound themes of mortality, meaning, and the way young people confront life's biggest questions with humor and grace.",
        tags: ["Romance", "Young Adult", "Contemporary"],
        featured: false,
        newArrival: false
    },
    {
        id: 49,
        title: "The Da Vinci Code",
        author: "Dan Brown",
        category: "Mystery",
        rating: 4.2,
        pages: 489,
        year: 2003,
        cover: "https://covers.openlibrary.org/b/id/8231475-L.jpg",
        description: "Harvard symbologist Robert Langdon is drawn into a murder mystery involving the Priory of Sion, the Knights Templar, and a secret society that has protected a shocking religious revelation for two thousand years, racing through Paris and London to uncover the truth while being pursued by those who would kill to keep it buried.",
        tags: ["Thriller", "Mystery", "Conspiracy"],
        featured: false,
        newArrival: false
    },
    {
        id: 50,
        title: "Angels & Demons",
        author: "Dan Brown",
        category: "Mystery",
        rating: 4.1,
        pages: 616,
        year: 2000,
        cover: "https://covers.openlibrary.org/b/id/8231478-L.jpg",
        description: "Harvard symbologist Robert Langdon is summoned to CERN to investigate the murder of a physicist and the theft of antimatter, uncovering a conspiracy involving the Illuminati, a secret society allegedly plotting revenge against the Catholic Church, in this high-octane prequel to The Da Vinci Code.",
        tags: ["Thriller", "Mystery", "Conspiracy"],
        featured: false,
        newArrival: false
    },
    {
        id: 51,
        title: "The Power of Habit",
        author: "Charles Duhigg",
        category: "Self-Help",
        rating: 4.3,
        pages: 371,
        year: 2012,
        cover: "https://covers.openlibrary.org/b/id/8231481-L.jpg",
        description: "Award-winning journalist Charles Duhigg presents a fascinating exploration of the science behind habit formation in individuals, organizations, and societies, introducing the habit loop (cue, routine, reward) and showing readers how to transform their lives by understanding and harnessing the power of keystone habits.",
        tags: ["Self-Help", "Psychology", "Productivity"],
        featured: false,
        newArrival: true
    },
    {
        id: 52,
        title: "Educated",
        author: "Tara Westover",
        category: "Biography",
        rating: 4.7,
        pages: 334,
        year: 2018,
        cover: "https://covers.openlibrary.org/b/id/8231484-L.jpg",
        description: "A powerful memoir about a young woman from rural Idaho who, despite growing up in a survivalist family with no formal education, gains admission to Cambridge and Harvard, ultimately choosing education over family loyalty in a story of self-invention, resilience, and the transformative power of learning.",
        tags: ["Memoir", "Education", "Inspiring"],
        featured: true,
        newArrival: true
    }
];

// Categories with icons
const categories = [
    { name: "Fiction", icon: "📖", count: 11, color: "#6366f1" },
    { name: "Mystery", icon: "🔍", count: 5, color: "#ec4899" },
    { name: "Science Fiction", icon: "🚀", count: 6, color: "#14b8a6" },
    { name: "Fantasy", icon: "🧙", count: 4, color: "#8b5cf6" },
    { name: "Romance", icon: "💕", count: 7, color: "#f43f5e" },
    { name: "Horror", icon: "👻", count: 4, color: "#1f2937" },
    { name: "Historical Fiction", icon: "🏛️", count: 3, color: "#d97706" },
    { name: "Non-Fiction", icon: "📚", count: 1, color: "#0891b2" },
    { name: "Biography", icon: "👤", count: 3, color: "#7c3aed" },
    { name: "Self-Help", icon: "💪", count: 2, color: "#059669" },
    { name: "Business", icon: "💼", count: 2, color: "#2563eb" },
    { name: "Children", icon: "🧸", count: 2, color: "#f97316" },
    { name: "Psychology", icon: "🧠", count: 1, color: "#6d28d9" },
    { name: "Philosophy", icon: "🤔", count: 1, color: "#475569" }
];

console.log("✅ Books data loaded! Total books:", booksData.length);
console.log("✅ Categories loaded! Total categories:", categories.length);